name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install SSH client
        run: sudo yum install -y openssh

      - name: Add SSH key to SSH agent
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd /var/www/html
            if [ ! -d ".git" ]; then
             echo "This is not a git repository. Cloning..."
             git clone https://github.com/Swetharamya3/color-flipper-front-end-code.git
           else
             echo "Git repository found. Pulling latest changes..."
             git pull origin main  # Pull latest changes from the git repository
          fi
            sudo chown -R apache:apache /var/www/html
            sudo systemctl restart httpd
          EOF 
