name: Send Email on Push

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install secure-smtplib
      - name: Send Email using SMTP
        run: |
          python -c "
          import smtplib
          from email.mime.text import MIMEText
          from email.mime.multipart import MIMEMultipart
          smtp_server = 'smtp.gmail.com'
          smtp_port = 587
          sender_email = '${{ secrets.GMAIL_SENDER_EMAIL }}'
          recipient_email = 'rajaswetha277@gmail.com'
          password = '${{ secrets.GMAIL_APP_PASSWORD }}'  # Gmail App Password for better security
          message = MIMEMultipart()
          message['From'] = sender_email
          message['To'] = recipient_email
          message['Subject'] = 'GitHub Actions Notification'
          body = 'This is a test email sent from GitHub Actions.'
          message.attach(MIMEText(body, 'plain'))
          try:
             server = smtplib.SMTP(smtp_server, smtp_port)
             server.starttls()  # Start TLS encryption
             server.login(sender_email, password)
             text = message.as_string()
             server.sendmail(sender_email, recipient_email, text)
             server.quit()
             print('Email sent successfully!')
          except Exception as e:
            print(f'Error sending email: {e}') "
