name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy whenever the main branch is updated

permissions:
  contents: write  # Needed to push to gh-pages branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js (if using static site generators like Jekyll/Hugo)
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Provided by GitHub Actions
        publish_dir: ./  # Directory to deploy (update if necessary)
